
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (SELECT MAX(SIZE_OF_COLONY) FROM ECOLI_DATA T2 WHERE YEAR(T2.DIFFERENTIATION_DATE) = YEAR(T1.DIFFERENTIATION_DATE)) - T1.SIZE_OF_COLONY AS YEAR_DEV, T1.ID
FROM ECOLI_DATA T1
ORDER BY YEAR ASC, YEAR_DEV ASC;