-- 코드를 입력하세요
SELECT DISTINCT(CC.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS CC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH ON CC.CAR_ID = CH.CAR_ID
WHERE CH.START_DATE LIKE '2022-10%' AND CC.CAR_TYPE = '세단'
ORDER BY CC.CAR_ID DESC;