-- 코드를 입력하세요
SELECT B.TITLE as TITLE, R.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY AS R, USED_GOODS_BOARD AS B
WHERE B.BOARD_ID = R.BOARD_ID AND B.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY CREATED_DATE ASC, TITLE ASC;