-- 코드를 작성해주세요
SELECT HR_D.DEPT_ID, HR_D.DEPT_NAME_EN, ROUND(AVG(HR_E.SAL)) AS AVG_SAL
FROM HR_DEPARTMENT AS HR_D
JOIN HR_EMPLOYEES AS HR_E ON HR_D.DEPT_ID = HR_E.DEPT_ID
GROUP BY HR_D.DEPT_ID, HR_D.DEPT_NAME_EN
ORDER BY AVG_SAL DESC;